name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  AWS_REGION: "eu-north-1"
  ECR_REGISTRY: "989005111810.dkr.ecr.eu-north-1.amazonaws.com"
  ECR_REPOSITORY: "counter-service-repo"
  IMAGE_NAME: "counter-service"
  IMAGE_TAG: "latest"
  FULL_IMAGE: "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
  KUBE_CONFIG_PATH: "$HOME/.kube/config"

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $FULL_IMAGE

      - name: Push Docker image
        run: |
          docker push $FULL_IMAGE

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p $(dirname "$KUBE_CONFIG_PATH")
          echo "${{ secrets.KUBE_CONFIG }}" > $KUBE_CONFIG_PATH

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
